### ISSUE TITLE
Huge market demand communication matters

### ISSUE THREAD

**Issue by woodadams** [prinsss/export-twitter-following-list#2]
Hello, your job is really great. It can easily export the Twitter follow list without being restricted by the Twitter API. 
     I am a practitioner in the encryption industry and often use Twitter. We most need to know that the people we follow have been new added. Which Twitter accounts are being followed (of course it is best to make statistics on the returned Twitter accounts, such as how many people have newly followed the same project at the same time), and notify us by email so that we can better follow up on the project. This plug-in has a huge demand in the encryption circle. 

   Please see if you can try to improve this . If you are interested, please contact me on Twitter @criswong1992
, thank you~

**Comment by prinsss** [comment]
Hi,

Thank you for being interested in this project. I'm aware of that the demand of following/followers analytics is huge.

However, this user script works by listening and parsing the requests sent by the Twitter Web App,
which uses its own internal APIs and authentication mechanisms.

We do not actively send requests to the API and we can't receive any data without user's operation
in the Web App, which means that the script is not capable for automated tasks like the public developer API.
(But you can still use [Selenium](https://www.selenium.dev/) or something to build browser automation on top of it.)

Hence, this project is mainly focused on personal usage and is not competent enough for using as an analytics tool.

Feel free to ask if you have any further questions. :)
